[workspace]
members = ["packages/*"]
default-members = ["packages/*"]
resolver = "2"
exclude = ["linkchecker"]        # part of the CI workflow

[workspace.dependencies]
walkdir = "2.3.1"
docopt = "1.1.0"
mdbook = "0.4.37"
serde = "1.0"
regex = "1.3.3"
lazy_static = "1.4.0"
flate2 = "1.0.13"
tar = "0.4.26"
