[[questions]]
id = "c5b27431-c318-4243-9621-cadacb737f5a"
type = "MultipleChoice"
prompt.prompt = """
True/false: this code will terminate and not loop forever or crash.

```
fn main() {
    let mut x = 0;
    'a: loop {
        x += 1;
        'b: loop {
            if x > 10 {
                continue 'a;
            } else {
                break 'b;
            }      
        }
        break;       
    }
}
```
"""
answer.answer = "True"
prompt.distractors = [ "False" ]
context = """
It will in fact terminate after the first iteration of the loop.
"""

[[questions]]
id = "46a52842-d4eb-4dc9-8885-f31a2f2f59b4"
type = "Tracing"
prompt.program = """
fn main() {
    let a = [5; 10];
    let mut sum = 0;
    for x in a {
        sum += x;
    }
    println!("{sum}");
}
"""
answer.doesCompile = true
answer.stdout = "50"
context = """
The array `a` has the element `5` repeated 10 times, therefore its sum is `50`. The answer is not `15` --- note that the syntax `[5; 10]` is different from `[5, 10]`.
"""