[[questions]]
id = "a48e524e-852c-400c-ae68-5c76a6761596"
type = "MultipleChoice"
prompt.prompt = "Which of the following statements is correct about the difference between using `let` and `const` to declare a variable?"
prompt.choices = [
  "They are just different syntaxes for declaring variables with the same semantics",
  "`const` can be used in the global scope, and `let` can only be used in a function",
  "The compiler will error if a `const` variable's name is not using `UPPER_SNAKE_CASE`",
  "A `const` can only be assigned to an atomic constant, not a expression involving computation"
]
answer.answer = 1

[[questions]]
id = "d209784f-cc52-4451-8049-ad204e89d587"
type = "Tracing"
prompt.program = """
const TWO: u32 = 1 + 1;
fn main() {
  println!("{TWO}");
}
"""
answer.doesCompile = true
answer.stdout = "2"
context = """
`const` variables are allowed to be defined outside of a function and to do limited forms of computation.
"""