[[questions]]
id = "dca33d34-6294-43f4-9267-fd62d7dce993"
type = "Tracing"
prompt.program = """
fn main() {
  let mut x: u32 = 1;
  {
    let mut x = x;
    x += 2;
  }
  println!("{x}");
}
"""
answer.doesCompile = true
answer.stdout = "1"
context = """
The statement `x += 2` only affects the shadowed `x` inside the inner curly braces, not the outer `x` on line 2.
"""

[[questions]]
id = "dca33d34-6294-43f4-9267-fd62d7dce993"
type = "Tracing"
prompt.program = """
fn main() {
  let mut x: u32 = 1;
  x = "Hello world";
  println!("{x}");
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
A variable cannot be assigned to a value of a different type than its original type.
"""
