[[questions]]
id = "23c95879-aae2-4121-bf89-21278f7b6ec6"
type = "MultipleChoice"
prompt.prompt = """
Which of the following is NOT a good reason to use a module?
"""
prompt.choices = [
  "Modules boost the runtime performance of interdependent code within the same module",
  "Modules group related code so programmers can more easily work on a large codebase",
  "Modules encapsulate implementation details that shouldn't be used by external clients",
  "Modules provide a scope to avoid naming conflicts across parts of a codebase"
]
answer.answer = 0
context = """
Modules have no effect on runtime, they are purely for compile-time organization.
"""
