[[questions]]
id = "c753bc38-0dc1-44d5-8b06-136fdbbc26d2"
type = "MultipleChoice"
prompt.prompt = """
When you run `cargo build` with no additional flags, which release profile is used by default?
"""
answer.answer = "`dev`"
prompt.distractors = [
    "`release`",
    "`build`",    
]
context = """
To minimize compile times, the default profile is `dev`. You should add `--release` if you want the `release` profile
for longer compile times but faster code execution. (There is no `build` profile).
"""