[[questions]]
id = "d172fc53-0220-4ff4-83c9-9c0a6834dd8e"
type = "MultipleChoice"
prompt.prompt = "What is 1 + 1? (Try clicking a wrong answer.)"
answer.answer = "2"
prompt.distractors = [ "0", "-999", "11" ]
context = """
See *Principia Mathematica* for an explanation of this fact.
"""