[package]
name = "trpl"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A support crate for The Rust Programming Language book"
readme = "README.md"
repository = "https://github.com/rust-lang/book"
authors = ["Chris Krycho <hello@chriskrycho.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
reqwest = "0.12"
scraper = "0.20"
tokio = { version = "1", default-features = false, features = [
    "fs",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-stream = "0.1"
